@startuml sequence
title Light Regulation: User sets Brightness
participant ca as "Core Application" <<Service>>
participant ba as "Bulb Adapter" <<Gateway Adapter>>
participant b as "Bulb" <<Device>>

ca -> ba: increase brightness
activate ba
ba -> ba: choose protocol
activate ba
ba -> b: increase brightness
deactivate ba
activate b
b->b: increase brightness
activate b
b --> ba: brightness increased
deactivate b
deactivate b
ba --> ca: brightness increased
deactivate ba
@enduml
